/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx.sample.project;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Application.launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Label l = new Label("Hello"); // this is just a text i guess
        Scene s = new Scene(l);
        primaryStage.setScene(s); // set scene to the primary stage
        primaryStage.show(); // performs actual rendering
    }
}
